# Generated by Django 4.2.2 on 2023-10-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Woj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
                ('symbol', models.PositiveSmallIntegerField(verbose_name='Numer Województwa')),
                ('update_date', models.DateField(verbose_name='Stan na')),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Województwa',
            },
        ),
    ]
